import Footer from "./Footer";
import Navbar from "./Navbar";
import { Sora } from "@next/font/google";
import Head from "next/head";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
});

interface LayoutProps {}

export default function Layout({}: LayoutProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${sora.variable} font-sans`}>
        <Navbar />
        {/* {children} */}
        childrween
        <Footer />
      </main>
    </>
  );
}
